export const DOCUMENT_TYPES = {
  "C.E": "C.E",
  DNI: "DNI",
  RUC: "RUC",
  CPP: "CPP"
}

export const PROCESSED_SALE_RESULTS = [
  "DERIVADO A ASIGNACIÓN",
  "ASIGNADO",
  "CARTA DE AUTORIZACIÓN POR FIMAR",
  "CARTA DE AUTORIZACIÓN FIRMADA",
  "VISITA TECNICA PROGRAMADA",
  "VISITA TECNICA REALIZADA",
  "INFORME TSS POR APROBAR",
  "OBRAS EN EL PREDIO",
  "HABILITADO",
  "RECHAZADO",
]

export const SERVICE_OPERATORS = {
  WIN: "WIN",
  NUBYX: "NUBYX",
  CLARO: "CLARO",
  WOW: "WOW",
  GPON: "GPON",
}

export const PREDIOS = {
  CASA: "CASA",
  EDIFICIO: "EDIFICIO"
}