export const departaments = [
  "ANCASH",
  "LA LIBERTAD",
  "LIMA",
];

const LIMA = ["BARRANCA",
  "CAJATAMBO",
  "CALLAO",
  "CAÑETE",
  "CANTA",
  "HUARAL",
  "HUAROCHIRI",
  "HUARA",
  "LIMA",
  "OYON",
  "YAUYOS"
]
const ANCASH = [
  "AIJA",
  "ANTONIO RAYMONDI",
  "ASUNCIÓN",
  "BOLOGNESI",
  "CARHUAZ",
  "CARLOS FERMIN FITZCARRALD",
  "CASMA",
  "CORONGO",
  "HUARAZ",
  "HUARI",
  "HUARMEY",
  "HUAYLAS",
  "MARISCAL LUZURIAGA",
  "OCROS",
  "PALLASCA",
  "POMABAMBA",
  "RECUAY",
  "SANTA",
  "SIHUAS",
  "YUNGAI",
]
const LIBERTAD = [
  "ASCOPE",
  "BOLIVAR",
  "CHEPEN",
  "GRAN CHIMÚ",
  "JULCAN",
  "OTUZCO",
  "PACASMAYO",
  "PATAZ",
  "SÁNCHEZ CARRIÓN",
  "SANTIAGO DE CHUCO",
  "TRUJILLO",
  "VIRU",
];

export const provincies = {
  LIMA: ["BARRANCA",
    "CAJATAMBO",
    "CALLAO",
    "CAÑETE",
    "CANTA",
    "HUARAL",
    "HUAROCHIRI",
    "HUARA",
    "LIMA",
    "OYON",
    "YAUYOS"
  ],
  ANCASH: [
    "AIJA",
    "ANTONIO RAYMONDI",
    "ASUNCIÓN",
    "BOLOGNESI",
    "CARHUAZ",
    "CARLOS FERMIN FITZCARRALD",
    "CASMA",
    "CORONGO",
    "HUARAZ",
    "HUARI",
    "HUARMEY",
    "HUAYLAS",
    "MARISCAL LUZURIAGA",
    "OCROS",
    "PALLASCA",
    "POMABAMBA",
    "RECUAY",
    "SANTA",
    "SIHUAS",
    "YUNGAI",
  ],
  "LA LIBERTAD": [
    "ASCOPE",
    "BOLIVAR",
    "CHEPEN",
    "GRAN CHIMÚ",
    "JULCAN",
    "OTUZCO",
    "PACASMAYO",
    "PATAZ",
    "SÁNCHEZ CARRIÓN",
    "SANTIAGO DE CHUCO",
    "TRUJILLO",
    "VIRU",
  ]
}

export const provincias = {
  LIMA: [
    "BARRANCA"
  ],

}

export const districts = {
  //ANCASH
  "AIJA": ["AIJA", "CORIS", "HUACLLAN", "LA MERCED", "SUCCHA"],
  "ANTONIO RAYMONDI": ["ACZO", "CHACCHO", "CHINGAS", "LLAMELLIN", "MIRGAS", "SAN JUAN DE RONTOY"],
  "ASUNCIÓN": ["ACOCHACA", "CHACAS"],
  "BOLOGNESI": ["ABELARDO PARDO LEZAMETA", "ANTONIO RAYMONDI", "AQUIA", "CAJACAY", "CANIS", "CHIQUIAN", "COLQUIOC", "HUALLANCA", "HUASTA", "HUAYLLACAYAN", "LA PRIMERAVERA", "MANGAS", "PACLLON", "SAN MIGUEL DE CORPANQUI", "TICLLOS"],
  "CARHUAZ": ["ACOPAMPA", "AMASHCA", "ANTA", "ATAQUERO", "CARHUAZ", "MARCARA", "PARIAHUANCA", "SAN MIGUEL DE ACO", "SHILLA", "TINCO", "YUNGAR"],
  "CARLOS FERMIN FITZCARRALD": ["SAN LUIS", "SAN NICOLAS", "YAUYA"],
  "CASMA": ["BUENA VISTA ALTA", "CASMA", "COMANDANTE NOEL", "YAUTAN"],
  "CORONGO": ["ACO", "BAMBAS", "CORONGO", "CUSCA", "HUARI", "LA PAMPA", "YANAC", "YUPAN"],
  "HUARAZ": ["COCHABAMBA", "COLCABAMBA", "HUANCHAY", "HUARAZ", "INDEPENDENCIA", "JANGAS", "LA LIBERTAD", "OLLEROS", "PAMPAS GRANDE", "PARIACOTO", "PIRA", "TARICA"],
  "HUARI": ["ANRA", "CAJAY", "CHAVIN DE HUANTAR", "HUACACHI", "HUACCHIS", "HUACHIS", "HUANTAR", "MASIN", "PAUCAS", "PONTO", "RAHUAPAMPA", "RAPAYAN", "SAN MARCOS", "SAN PEDRO DE CHANA", "UCO"],
  "HUARMEY": ["COCHAPETI", "CULEBRAS", "HUARMEY", "HUAYAN", "MALVAS"],
  "HUAYLAS": ["CARAZ", "HUALLANCA", "HUATA", "HUYLAS", "MATO", "PAMPAROMAS", "PUEBLO LIBRE", "SANTA CRUZ", "SANTO TORIBIO", "YURACMARCA"],
  "MARISCAL LUZURIAGA": ["CASCA", "ELEAZAR GUZMÁN BARRON", "FIDEL OLIVAR ESCUDERO", "LLAMA", "LLUMPA", "LUCMA", "MUSGA", "PISCOBAMBA"],
  "OCROS": ["ACAS", "CAJAMARQUILLA", "CARHUAPAMPA", "COCHAS", "CONGAS", "LLIPA", "ACROS", "SAN CRISTÓBAL DE RAJAN", "SAN PEDRO", "SANTIAGO DE CHILCAS"],
  "PALLASCA": ["BOLOGNESI", "CABANA", "CONCHUCOS", "HUACASCHUQUE", "HUANDOVAL", "LACABAMBA", "LLAPO", "PALLASCA", "PAMPAS", "SANTA ROSA", "TAUCA"],
  "POMABAMBA": ["HUAYLLAN", "PAROBAMBA", "POMABAMBA", "QUINUABAMBA"],
  "RECUAY": ["CATAC", "COTAPARACO", "HUAYLLAPAMPA", "LLACLLIN", "MARCA", "PAMPAS CHICO", "PARARIN", "RECUAY", "TAPACOCHA", "TICAPAMPA"],
  "SANTA": ["CÁCERES DEL PERÚ", "CHIMBOTE", "COISHCO", "MACATE", "MORO", "NEPEÑA", "NUEVO CHIMBOTE", "SAMANCO", "SANTA",],
  "SIHUAS": ["ACOBAMBA", "ALFONSO UGARTE", "CASHAPAMPA", "CHINGALPO", "HUAYLLABAMBA", "QUICHES", "RAGASH", "SAN JUAN", "SICSIBAMBA", "SIHUAS"],
  "YUNGAI": ["CASCAPARA", "MANCOS", "MATACOTO", "QUILLO", "RANRAHIRCA", "SHUPLUY", "YANAMA", "YUNGAY"],
  //LA LIBERTAD
  "ASCOPE": ["ASCOPE", "CASA GRANDE", "CHICAMA", "CHOCOPE", "MAGDALENA DE CAO", "PAIJAN", "RÁZURI", "SANTIAGO DE CAO"],
  "BOLIVAR": ["BAMBAMARCA", "BOLIVAR", "CONDORMARCA", "LONGOTEA", "UCHUMARCA", "UCUNCHA"],
  "CHEPEN": ["CHEPEN", "PACANGA", "PUEBLO NUEVO"],
  "GRAN CHIMÚ": ["CASCAS", "LUCMA", "MARMOT", "SAYAPUYO"],
  "JULCAN": ["CALAMARCA", "CARABAMBA", "HUASO", "JULCAN"],
  "OTUZCO": ["AGALLPAMPA", "CHARAT", "HUARANCHAL", "LA CUESTA", "MACHE", "OTUZCO", "PARANDAY", "SALPO", "SINSICAP", "USQUIL"],
  "PACASMAYO": ["GUADALUPE", "JEQUETEPEQUE", "PACASMAYO", "SAN JOSÉ", "SAN PEDRO DE LLOC"],
  "PATAZ": ["BULDIBUYO", "CHILLIA", "HUANCASPATA", "HUAYLILLAS", "HUAYO", "ONGON", "PARCOY", "PATAZ", "PIAS", "SANTIAGO DE CHALLAS", "TAURIJA", "TAYABAMBA", "URPAY"],
  "SÁNCHEZ CARRIÓN": ["CHUGAY", "COCHORCO", "CURGOS", "HUAMACHUCO", "MARCABAL", "SANAGORAN", "SARIN", "SARTINBAMBA"],
  "SANTIAGO DE CHUCO": ["ANGASMARCA", "CACHICADAN", "MOLLEBAMBA", "MOLLEPATA", "QUIRUVILCA", "SANTA CRUZ DE CHUCA", "SANTA CRUZ DE CHUCO", "SITABAMBA"],
  "TRUJILLO": ["EL PORVENIR", "FLORENCIA DE MORA", "HUANCHACO", "LA ESPERANZA", "LAREDO", "MOCHE", "POROTO", "SALAVERRY", "SIMBAL", "TRUJILLO", "VICTOR LARCO HERRERA"],
  "VIRU": ["CHAO", "GUADALUPITO", "VIRU"],
  //LIMA
  "BARRANCA": ["BARRANCA", "PARAMONGA", "PATIVILCA", "SUPE", "SUPE PUERTO"],
  "CAJATAMBO": ["CAJATAMBO", "COPA", "CORGOR", "HUANCAPON", "MANAS"],
  "CALLAO": ["BELLAVISTA", "CALLAO", "CARMEN DE LA LEGUA-REYNOSO", "LA PERLA", "LA PUNTA", "VENTANILLA"],
  "CAÑETE": ["ASIA", "CALANGO", "CERRO AZUL", "CHILCA", "COAYLLO", "IMPERIAL", "LUNAHUANA", "MALA", "NUEVO IMPERIAL", "PACARAN", "QUILMANA", "SAN ANTONIO", "SAN LUIS", "SAN VICENTE DE CAÑETE", "SANTA CRUZ DE FLORES", "ZÚÑIGA"],
  "CANTA": ["ARAHUAY", "CANTA", "HUAMANTANGA", "HUAROS", "LACHAQUI", "SAN BUENAVENTURA", "SANTA ROSA DE QUIVES"],
  "HUARAL": ["ATAVILLOS ALTOS", "ATAVILLOS BAJOS", "AUCALLAMA", "CHANCAY", "HUARAL", "IHUARI", "LAMPIAN", "PACARAOS", "SAN MIGUEL DE ACOS", "SANTA CRUZ DE ANDAMARCA", "SUMBILCA", "VEINTISIETE DE NOVIEMBRE"],
  "HUAROCHIRI": ["ANTIOQUIA", "CALLAHUANCA", "CARAMPOMA", "CHICLA", "CUENCA", "HUACHUPAMPA", "HUANZA", "HUAROCHIRI", "LAHUAYTAMBO", "LANGA", "LARAOS", "MARIATANA", "MATUCANA", "RICARDO PALMA", "SAN ANDRES DE TUPICOCHA", "SAN ANTONIO", "SAN BARTOLOMÉ", "SAN DAMIAN", "SAN JUAN DE IRIS", "SAN JUAN DE TANTARANCHE", "SAN LORENZO DE QUINTI", "SAN MATEO", "SAN MATEO DE OTAO", "SAN PEDRO DE CASTA", "SAN PEDRO DE HUANCAYRE", "SANGALLAYA", "SANTA CRUZ DE COCACHACRA", "SANTA EULALIA", "SANTIAGO DE ANCHUCAYA", "SANTIAGO DE TUNA", "SANTO DOMINGO DE LOS OLLEROS", "SURCO",],
  "HUARA": ["AMBAR", "CALETA DE CARQUIN", "CHECRAS", "HUACHO", "HUALMAY", "HUARA", "LEONCIO PRADO", "PACCHO", "SANTA LEONOR", "SANTA MARIA", "SAYAN", "VEGUETA"],
  "LIMA": ["ANCÓN", "ATE", "BARRANCO", "BREÑA", "CARABAYLLO", "CERCADO DE LIMA", "CHACLACAYO", "CHORRILLOS", "CIENEGUILLA", "COMAS", "EL AGUSTINO", "INDEPENDENCIA", "JESÚS MARÍA", "LA MOLINA", "LA VICTORIA", "LINCE", "LOS OLIVOS", "LURIGANCHO-CHOSICA", "LURÍN", "MAGDALENA DEL MAR", "MIRAFLORES", "PACHACÁMAC", "PUCUSANA", "PUEBLO LIBRE", "PUENTE PIEDRA", "PUNTA HERMOSA", "PUNTA NEGRA", "RÍMAC", "SAN BARTOLO", "SAN BORJA", "SAN ISIDRO", "SAN LUIS", "SAN JUAN DE LURIGANCHO", "SAN JUAN DE MIRAFLORES", "SAN MARTIN DE PORRES", "SAN MIGUEL", "SANTA ANITA", "SANTA MARÍA DEL MAR", "SANTA ROSA", "SANTIAGO DE SURCO", "SURQUILLO", "VILLA EL SALVADOR", "VILLA MARÍA DEL TRIUNFO"],
  "OYON": ["ANDAJES", "CAUJUL", "COCHAMARCA", "NAVAN", "OYON", "PACHANGARA"],
  "YAUYOS": ["ALIS", "ALLAUCA", "AYAVIRI", "AZÁNGARO", "CACRA", "CARANIA", "CATAHUASI", "CHOCOS", "COCHAS", "COLONIA", "HONGOS", "HUAMPARA", "HUANCAYA", "HUAÑEC", "HUANGASCAR", "HUANTAN", "LARAOS", "LINCHA", "MADEAN", "MIRAFLORES", "OMAS", "PUTINZA", "QUINCHES", "QUINOCAY", "SAN JOAQUÍN", "SAN PEDRO DE PILAS", "TANTA", "TAURIPAMPA", "TOMAS", "TUPE", "VIÑAC", "VITIS", "YAUYOS"],
}
export const distritos = [
  //ANCASH
  { AIJA: "AIJA", id: "AIJA" }

]

export const provinciesAncash = [
  "AIJA",
  "ANTONIO RAYMONDI",
  "ASUNCIÓN",
  "BOLOGNESI",
  "CARHUAZ",
  "CARLOS FERMIN FITZCARRALD",
  "CASMA",
  "CORONGO",
  "HUARAZ",
  "HUARI",
  "HUARMEY",
  "HUAYLAS",
  "MARISCAL LUZARIAGA",
  "OCROS",
  "PALLASCA",
  "POMA BAMBA",
  "RECUAY",
  "SANTA",
  "SIHUAS",
  "YUNGAI",
];
export const provinciesLima = [
  "BARRANCA",
  "CAJATAMBO",
  "CALLAO",
  "CAÑETE",
  "CANTA",
  "HUARAL",
  "HUAROCHIRI",
  "HUARA",
  "LIMA",
  "OYON",
  "YAUYOS",
];

export const provinciesLaLibertad = [
  "ASCOPE",
  "BOLIVAR",
  "CHEPEN",
  "GRAN CHIMU",
  "JULCAN",
  "OTUZCO",
  "PACASMAYO",
  "PATAZ",
  "SANCHEZ CARRION",
  "SANTIAGO DE CHUCO",
  "TRUJILLO",
  "VIRU",
];

export const PLANS_PACKAGES = [
  {
    megas: 50,
    price: 79,
    velocity: "MBPS",
    currency: "S",
    id: 1
  },
  {
    megas: 75,
    price: 89,
    velocity: "MBPS",
    currency: "S",
    id: 2

  },
  {
    megas: 100,
    price: 99,
    velocity: "MBPS",
    currency: "S",
    id: 3
  },
  {
    megas: 150,
    price: 119,
    velocity: "MBPS",
    currency: "S",
    id: 4
  },
  {
    megas: 200,
    price: 129,
    velocity: "MBPS",
    currency: "S",
    id: 5
  },
  {
    megas: 300,
    price: 169,
    velocity: "MBPS",
    currency: "S",
    id: 6
  },
  {
    megas: 600,
    price: 259,
    velocity: "MBPS",
    currency: "S",
    id: 7
  },
  {
    megas: 1000,
    price: 459,
    velocity: "MBPS",
    currency: "S",
    id: 8
  },
  {
    megas: 140,
    price: 109,
    velocity: "MBPS",
    currency: "S",
    id: 9
  },
];

export const PLANS_ADITIONAL = [{ name: "MONO", price: 0, id: 1 }, { name: "DUO", price: 15, id: 2 }, { name: "TRIO", price: 20, id: 3 }]

export const RESULTS = [
  "VENTA",
  "INGRESADA",
  "PAGADA",
  "INSTALADA",
  "ZONA SATURADA",
  "ARBITRAJE",
  "NO GRABO",
  "SIN FOTO",
  "RECHAZADA",
]