const PROCESSED_SALE_RESULTS = [
  "DERIVADO A ASIGNACIÓN",
  "ASIGNADO",
  "CARTA DE AUTORIZACIÓN POR FIMAR",
  "CARTA DE AUTORIZACIÓN FIRMADA",
  "VISITA TECNICA PROGRAMADA",
  "VISITA TECNICA REALIZADA",
  "OBRAS EN EL PREDIO",
  "HABILITADO",
  "RECHAZADO",
]

export default PROCESSED_SALE_RESULTS
